# Generated by Django 5.0.3 on 2024-04-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelCar',
            new_name='Car',
        ),
    ]
