# Generated by Django 5.0.3 on 2024-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_purchase', '0002_rename_modelcar_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealers',
            field=models.ManyToManyField(related_name='cars', to='dealer_purchase.dealer'),
        ),
    ]
